export const ROUTES = {
  OPENING: '/opening',
  LOGIN: '/login',
  CREATE_ACCOUNT: '/create-account',
  CHANGE_PASSCODE: '/change-passcode',
  TODAY: '/today',
  FOOD: '/food',
  FOOD_ADD_VIEW: '/food/add',
  CREATE_FOOD: '/food/create-food',
  CREATE_MEAL: '/food/create-meal',
  ACTIVITIES: '/activities',
  LOG_ACTIVITY: '/log-activity',
  GYM_DIARY: '/gym-diary',
  WORKOUT_SESSIONS: '/workout-sessions/:sessionId',
  WORKOUT_DASHBOARD: '/workout-dashboard',
  ADD_WORKOUT_DAY: '/workout-dashboard/add-workout-day',
  WORKOUT_DAY_EXERCISES: '/workout-dashboard/:workoutDayId/exercises',
  EXERCISE_SUMMARY: '/workout-dashboard/:workoutDayId/exercises/:exerciseId',
  ACTION: '/action',
  GYM_LIVE: '/gym-live',
  MORE: '/more',
}